"""Postgres schema and pool helper (asyncpg)."""

from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

import asyncpg

from bot import config

SCHEMA = """
CREATE TABLE IF NOT EXISTS schools (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS admins (
    telegram_id BIGINT PRIMARY KEY,
    school_id   BIGINT NOT NULL REFERENCES schools(id),
    class_name  TEXT NOT NULL,
    added_by    BIGINT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS students (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id  BIGINT NOT NULL REFERENCES schools(id),
    class_name TEXT NOT NULL,
    name       TEXT NOT NULL,
    position   INTEGER NOT NULL DEFAULT 0,
    is_active  BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (school_id, class_name, name)
);

CREATE TABLE IF NOT EXISTS records (
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    date       TEXT NOT NULL,
    status     TEXT NOT NULL CHECK (status IN ('O', 'O1')),
    PRIMARY KEY (student_id, date)
);

CREATE TABLE IF NOT EXISTS board_sessions (
    telegram_id BIGINT NOT NULL,
    date        TEXT NOT NULL,
    chat_id     BIGINT NOT NULL,
    message_id  BIGINT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'open',
    PRIMARY KEY (telegram_id, date)
);

CREATE TABLE IF NOT EXISTS settings (
    telegram_id     BIGINT PRIMARY KEY,
    morning_time    TEXT NOT NULL DEFAULT '07:40',
    excel_enabled   BOOLEAN NOT NULL DEFAULT FALSE,
    excel_day       TEXT NOT NULL DEFAULT 'last',
    excel_time      TEXT NOT NULL DEFAULT '16:00',
    excel_last_sent TEXT
);

CREATE TABLE IF NOT EXISTS auto_skip (
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    weekday    INTEGER NOT NULL CHECK (weekday BETWEEN 0 AND 6),
    PRIMARY KEY (student_id, weekday)
);
"""


async def _init_pool() -> asyncpg.Pool:
    """Create and return a new asyncpg connection pool."""
    return await asyncpg.create_pool(
        config.DATABASE_URL,
        min_size=config.DB_POOL_MIN,
        max_size=config.DB_POOL_MAX,
        command_timeout=60,
    )


_pool: asyncpg.Pool | None = None


def _ensure_pool() -> asyncpg.Pool:
    """Return the existing pool or raise if not initialised."""
    if _pool is None:
        raise RuntimeError("DB pool not initialised — call init_db() first")
    return _pool


@asynccontextmanager
async def connect() -> AsyncIterator[asyncpg.Connection]:
    """Acquire a connection from the pool; auto-release on exit."""
    pool = _ensure_pool()
    conn = await pool.acquire()
    try:
        yield conn
    finally:
        await pool.release(conn)


async def init_db() -> None:
    """Initialise the schema: create the pool and run migrations."""
    global _pool
    _pool = await _init_pool()
    async with _pool.acquire() as conn:
        await conn.execute(SCHEMA)


async def close_pool() -> None:
    """Close the connection pool; call on bot shutdown."""
    global _pool
    if _pool is not None:
        await _pool.close()
        _pool = None