services:
  lunch-bot:
    build: .
    container_name: lunchbot
    restart: unless-stopped
    env_file: .env
    networks:
      - postgres_net

networks:
  postgres_net:
    external: true
    name: postgres_net
